# CircleCI configuration file
version: 2.1

jobs:

  build:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - run: checkout
      - run: echo "npm run lint"
      - cache
      - save_cache:
          key:
            README-{{ .Branch }}-{{ .Revision }}
          paths:
            - README.md

  test:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - run: echo "npm run test"

  analyze:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - run: echo "npm run audit"
      - restore_cache:
          keys:
            README-{{ .Branch }}-{{ .Revision }}
      - run: cat README.md
