# CircleCI configuration file
version: 2.1

jobs:
  # first job
  print_hello:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo ">>> 1.step"
      - run: echo "hello"
      - run: echo "<<<<<<<<<<"

  # second job
  print_world:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: 
        name: print world
        command: | 
          echo ">>> 2.step"
          echo "world"
          echo "<<<<<<<<<<"
 
workflows:
  # Name of workflow
  my_workflow_1:
    # List of jobs that will run
    jobs:
      - print_hello
    requires: [print_hello]
      - print_world
