# CircleCI configuration file
version: 2.1

jobs:
  # first job
  print_hello:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "--- 1.step"
      - run: echo "hello"
      - run: echo "----------"

  # second job
  print_world:
    docker:
     - image: cimg/base:2022.05
    environment:
      CUSTOM_MESSAGE: "<< pipeline.project.git_url >> :: << pipeline.trigger_parameters.gitlab.commit_message>>"
    steps:
      - run: 
          name: print world
          command: | 
            echo "--- 2.step"
            echo "world $CUSTOM_MESSAGE"
            echo "value from UI: $UI_ENV_VAR "
            echo "----------"
  
  # third job
  save_result_to_workspace:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run:
          name: create file in workspace
          command: |
            mkdir workspace
            echo "-- 3.step"
            echo "third job value" > workspace/third-job.output.txt
            echo "---------"
      - persist_to_workspace:
          root: workspace
          paths:
            - third-job.output.txt
  
  # fourth job
  read_result_from_workspace:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run:
          name: read content of file from shared workspace
          command: |
            echo "-- 4.step"
            cat /workspace_shared/third-job.output.txt
            echo "---------"
      - attach_workspace:
          at: /workspace_shared
    

workflows:
  # Name of workflow
  my_workflow_1:
    jobs:
      - print_hello
      - print_world:
          requires: 
            - print_hello
      - save_result_to_workspace
      - read_result_from_workspace:
          requires:
            - save_result_to_workspace
